### 2020 ~ 2022 결혼 건수 데이터를 활용해서 결혼 증감율 계산

In [1]:
import pandas as pd
# encoding = 'euc-kr', index_col = '연령별' --> csv파일 불러오기

In [5]:
data2020 = pd.read_csv('./data/2020.csv', encoding = 'euc-kr', index_col = '연령별')
data2021 = pd.read_csv('./data/2021.csv', encoding = 'euc-kr', index_col = '연령별')
data2022 = pd.read_csv('./data/2022.csv', encoding = 'euc-kr', index_col = '연령별')
data2020.head(10)    #예시 데이터 보고 싶을떄 사용.(10을 넣으면 위에서 부터 앞에서부터 10개를 볼수있음)
                     #tail쓰면 뒤에서부터 볼수있다.

       남편    아내
연령별
15      1    16
16     10    27
17     18    80
18     60   471
19    193   921
20    269  1070
21    476  1370
22    789  2045
23   1248  3089
24   2163  4942

In [6]:
# 데이터 모양 확인
print(data2020.shape)
print(data2021.shape)
print(data2022.shape)

(61, 2)
(62, 2)
(61, 2)

In [12]:
# 데이터 분석을 할 때에는 데이터의 환경을 동일시 시켜주는 것이 좋다.
# 2021년 데이터에 어떤 문제가 있는지 인덱스를 나열해보자.
print(data2020.index)
print(data2021.index)  #2021이 문자 데이터 상태라서 숫자 형태로 바꿔줘야 한다
print(data2022.index)

RangeIndex(start=15, stop=76, step=1, name='연령별')
Index(['15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26',
       '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38',
       '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50',
       '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62',
       '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74',
       '75'],
      dtype='str', name='연령별')
RangeIndex(start=15, stop=76, step=1, name='연령별')

In [17]:
# 2021년 데이터에서 "미상" 이라는 데이터를 삭제해보자
#data2021.drop('미상', inplace = True) 써서 한번 삭제 했기 때문에 또 실행하면 에러뜸.
print(data2021.index)                #데이터를 먼저 나열하고 온점으로 들어가서 사용할 함수 적기(웬만하면 함수 뒤엔 소괄호가 붙어있다)

Index(['15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26',
       '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38',
       '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50',
       '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62',
       '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74',
       '75'],
      dtype='str', name='연령별')

In [19]:
print(data2020.shape)
print(data2021.shape)  #이렇게 쉐잎을 일치시켜서 데이터 분석을 할 준비를 마친다
print(data2022.shape)

(61, 2)
(61, 2)
(61, 2)

In [20]:
data2021.index #문자열 형태를 띄고 있으므로 -> 숫자 형태로 바꿔주자

Index(['15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26',
       '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38',
       '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50',
       '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62',
       '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74',
       '75'],
      dtype='str', name='연령별')

In [28]:
data2021.index = data2021.index.astype("int64")
data2021.index

Index([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75],
      dtype='int64', name='연령별')

In [30]:
print(data2020.index)
print(data2021.index)  # 형태가 좀 달라서 같은지 아닌지 증거가 없다

data2020.index == data2021.index #불리안 연산자로 확인

RangeIndex(start=15, stop=76, step=1, name='연령별')
Index([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75],
      dtype='int64', name='연령별')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [39]:
# 1번 문제. 연령 별 남편 수와 아내의 수를 더한 합계를 우측에 만들어 보자
# 컬럼 : "남편", "아내", "합계'
# data2020, 2021, 2022에 모두 적용

data = pd.concat([data2020, data2021, data2022])
data["합계"] = data["남편"] + data["아내"]
data

      남편   아내    합계
연령별
15     1   16    17
16    10   27    37
17    18   80    98
18    60  471   531
19   193  921  1114
..   ...  ...   ...
71   137  109   246
72   188  119   307
73   156   99   255
74   145   86   231
75   163   79   242

[183 rows x 3 columns]

In [ ]:
# 2번 문제. 연령에 대해서 라벨링 -> 범주화시키기
# bins = [-1, 19, 41, 100], Labels = ['청소년', '청년', '중장년']

ages =

In [41]:
data2020.shape

(61, 2)